name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm install
      - run: npm test

      - name: Coveralls
                uses: coverallsapp/github-action@1.1.2
                with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/lcov.info
                  flag-name: run-${{ matrix.node }}